// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.0
// source: proto/schedulr.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Appointments struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Appointments *[]*Appointment        `protobuf:"bytes,1,rep,name=appointments,proto3"`
	xxx_hidden_NextCursor   *string                `protobuf:"bytes,2,opt,name=nextCursor,proto3,oneof"`
	XXX_raceDetectHookData  protoimpl.RaceDetectHookData
	XXX_presence            [1]uint32
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Appointments) Reset() {
	*x = Appointments{}
	mi := &file_proto_schedulr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Appointments) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Appointments) ProtoMessage() {}

func (x *Appointments) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedulr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Appointments) GetAppointments() []*Appointment {
	if x != nil {
		if x.xxx_hidden_Appointments != nil {
			return *x.xxx_hidden_Appointments
		}
	}
	return nil
}

func (x *Appointments) GetNextCursor() string {
	if x != nil {
		if x.xxx_hidden_NextCursor != nil {
			return *x.xxx_hidden_NextCursor
		}
		return ""
	}
	return ""
}

func (x *Appointments) SetAppointments(v []*Appointment) {
	x.xxx_hidden_Appointments = &v
}

func (x *Appointments) SetNextCursor(v string) {
	x.xxx_hidden_NextCursor = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 1, 2)
}

func (x *Appointments) HasNextCursor() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 1)
}

func (x *Appointments) ClearNextCursor() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 1)
	x.xxx_hidden_NextCursor = nil
}

type Appointments_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Appointments []*Appointment
	NextCursor   *string
}

func (b0 Appointments_builder) Build() *Appointments {
	m0 := &Appointments{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Appointments = &b.Appointments
	if b.NextCursor != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 1, 2)
		x.xxx_hidden_NextCursor = b.NextCursor
	}
	return m0
}

type Appointment struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_BookingId    string                 `protobuf:"bytes,1,opt,name=bookingId,proto3"`
	xxx_hidden_Title        string                 `protobuf:"bytes,2,opt,name=title,proto3"`
	xxx_hidden_ScheduledFor *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=scheduledFor,proto3"`
	xxx_hidden_Duration     *durationpb.Duration   `protobuf:"bytes,4,opt,name=duration,proto3"`
	xxx_hidden_ScheduledAt  *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=scheduledAt,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Appointment) Reset() {
	*x = Appointment{}
	mi := &file_proto_schedulr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Appointment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Appointment) ProtoMessage() {}

func (x *Appointment) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedulr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Appointment) GetBookingId() string {
	if x != nil {
		return x.xxx_hidden_BookingId
	}
	return ""
}

func (x *Appointment) GetTitle() string {
	if x != nil {
		return x.xxx_hidden_Title
	}
	return ""
}

func (x *Appointment) GetScheduledFor() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_ScheduledFor
	}
	return nil
}

func (x *Appointment) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.xxx_hidden_Duration
	}
	return nil
}

func (x *Appointment) GetScheduledAt() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_ScheduledAt
	}
	return nil
}

func (x *Appointment) SetBookingId(v string) {
	x.xxx_hidden_BookingId = v
}

func (x *Appointment) SetTitle(v string) {
	x.xxx_hidden_Title = v
}

func (x *Appointment) SetScheduledFor(v *timestamppb.Timestamp) {
	x.xxx_hidden_ScheduledFor = v
}

func (x *Appointment) SetDuration(v *durationpb.Duration) {
	x.xxx_hidden_Duration = v
}

func (x *Appointment) SetScheduledAt(v *timestamppb.Timestamp) {
	x.xxx_hidden_ScheduledAt = v
}

func (x *Appointment) HasScheduledFor() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ScheduledFor != nil
}

func (x *Appointment) HasDuration() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Duration != nil
}

func (x *Appointment) HasScheduledAt() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ScheduledAt != nil
}

func (x *Appointment) ClearScheduledFor() {
	x.xxx_hidden_ScheduledFor = nil
}

func (x *Appointment) ClearDuration() {
	x.xxx_hidden_Duration = nil
}

func (x *Appointment) ClearScheduledAt() {
	x.xxx_hidden_ScheduledAt = nil
}

type Appointment_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	BookingId    string
	Title        string
	ScheduledFor *timestamppb.Timestamp
	Duration     *durationpb.Duration
	ScheduledAt  *timestamppb.Timestamp
}

func (b0 Appointment_builder) Build() *Appointment {
	m0 := &Appointment{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_BookingId = b.BookingId
	x.xxx_hidden_Title = b.Title
	x.xxx_hidden_ScheduledFor = b.ScheduledFor
	x.xxx_hidden_Duration = b.Duration
	x.xxx_hidden_ScheduledAt = b.ScheduledAt
	return m0
}

type ScheduleAppointmentRequest struct {
	state                   protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Title        string                 `protobuf:"bytes,1,opt,name=title,proto3"`
	xxx_hidden_ScheduledFor *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=scheduledFor,proto3"`
	xxx_hidden_Duration     *durationpb.Duration   `protobuf:"bytes,3,opt,name=duration,proto3"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *ScheduleAppointmentRequest) Reset() {
	*x = ScheduleAppointmentRequest{}
	mi := &file_proto_schedulr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScheduleAppointmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScheduleAppointmentRequest) ProtoMessage() {}

func (x *ScheduleAppointmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedulr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ScheduleAppointmentRequest) GetTitle() string {
	if x != nil {
		return x.xxx_hidden_Title
	}
	return ""
}

func (x *ScheduleAppointmentRequest) GetScheduledFor() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_ScheduledFor
	}
	return nil
}

func (x *ScheduleAppointmentRequest) GetDuration() *durationpb.Duration {
	if x != nil {
		return x.xxx_hidden_Duration
	}
	return nil
}

func (x *ScheduleAppointmentRequest) SetTitle(v string) {
	x.xxx_hidden_Title = v
}

func (x *ScheduleAppointmentRequest) SetScheduledFor(v *timestamppb.Timestamp) {
	x.xxx_hidden_ScheduledFor = v
}

func (x *ScheduleAppointmentRequest) SetDuration(v *durationpb.Duration) {
	x.xxx_hidden_Duration = v
}

func (x *ScheduleAppointmentRequest) HasScheduledFor() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_ScheduledFor != nil
}

func (x *ScheduleAppointmentRequest) HasDuration() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Duration != nil
}

func (x *ScheduleAppointmentRequest) ClearScheduledFor() {
	x.xxx_hidden_ScheduledFor = nil
}

func (x *ScheduleAppointmentRequest) ClearDuration() {
	x.xxx_hidden_Duration = nil
}

type ScheduleAppointmentRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Title        string
	ScheduledFor *timestamppb.Timestamp
	Duration     *durationpb.Duration
}

func (b0 ScheduleAppointmentRequest_builder) Build() *ScheduleAppointmentRequest {
	m0 := &ScheduleAppointmentRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_Title = b.Title
	x.xxx_hidden_ScheduledFor = b.ScheduledFor
	x.xxx_hidden_Duration = b.Duration
	return m0
}

type ListAppointmentsRequest struct {
	state                  protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Cursor      *string                `protobuf:"bytes,1,opt,name=cursor,proto3,oneof"`
	xxx_hidden_Limit       int32                  `protobuf:"varint,2,opt,name=limit,proto3"`
	xxx_hidden_Before      *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=before,proto3,oneof"`
	xxx_hidden_After       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=after,proto3,oneof"`
	XXX_raceDetectHookData protoimpl.RaceDetectHookData
	XXX_presence           [1]uint32
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ListAppointmentsRequest) Reset() {
	*x = ListAppointmentsRequest{}
	mi := &file_proto_schedulr_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAppointmentsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAppointmentsRequest) ProtoMessage() {}

func (x *ListAppointmentsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedulr_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *ListAppointmentsRequest) GetCursor() string {
	if x != nil {
		if x.xxx_hidden_Cursor != nil {
			return *x.xxx_hidden_Cursor
		}
		return ""
	}
	return ""
}

func (x *ListAppointmentsRequest) GetLimit() int32 {
	if x != nil {
		return x.xxx_hidden_Limit
	}
	return 0
}

func (x *ListAppointmentsRequest) GetBefore() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_Before
	}
	return nil
}

func (x *ListAppointmentsRequest) GetAfter() *timestamppb.Timestamp {
	if x != nil {
		return x.xxx_hidden_After
	}
	return nil
}

func (x *ListAppointmentsRequest) SetCursor(v string) {
	x.xxx_hidden_Cursor = &v
	protoimpl.X.SetPresent(&(x.XXX_presence[0]), 0, 4)
}

func (x *ListAppointmentsRequest) SetLimit(v int32) {
	x.xxx_hidden_Limit = v
}

func (x *ListAppointmentsRequest) SetBefore(v *timestamppb.Timestamp) {
	x.xxx_hidden_Before = v
}

func (x *ListAppointmentsRequest) SetAfter(v *timestamppb.Timestamp) {
	x.xxx_hidden_After = v
}

func (x *ListAppointmentsRequest) HasCursor() bool {
	if x == nil {
		return false
	}
	return protoimpl.X.Present(&(x.XXX_presence[0]), 0)
}

func (x *ListAppointmentsRequest) HasBefore() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Before != nil
}

func (x *ListAppointmentsRequest) HasAfter() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_After != nil
}

func (x *ListAppointmentsRequest) ClearCursor() {
	protoimpl.X.ClearPresent(&(x.XXX_presence[0]), 0)
	x.xxx_hidden_Cursor = nil
}

func (x *ListAppointmentsRequest) ClearBefore() {
	x.xxx_hidden_Before = nil
}

func (x *ListAppointmentsRequest) ClearAfter() {
	x.xxx_hidden_After = nil
}

type ListAppointmentsRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	Cursor *string
	Limit  int32
	Before *timestamppb.Timestamp
	After  *timestamppb.Timestamp
}

func (b0 ListAppointmentsRequest_builder) Build() *ListAppointmentsRequest {
	m0 := &ListAppointmentsRequest{}
	b, x := &b0, m0
	_, _ = b, x
	if b.Cursor != nil {
		protoimpl.X.SetPresentNonAtomic(&(x.XXX_presence[0]), 0, 4)
		x.xxx_hidden_Cursor = b.Cursor
	}
	x.xxx_hidden_Limit = b.Limit
	x.xxx_hidden_Before = b.Before
	x.xxx_hidden_After = b.After
	return m0
}

type GetAppointmentRequest struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_BookingId string                 `protobuf:"bytes,1,opt,name=bookingId,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetAppointmentRequest) Reset() {
	*x = GetAppointmentRequest{}
	mi := &file_proto_schedulr_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAppointmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAppointmentRequest) ProtoMessage() {}

func (x *GetAppointmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedulr_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *GetAppointmentRequest) GetBookingId() string {
	if x != nil {
		return x.xxx_hidden_BookingId
	}
	return ""
}

func (x *GetAppointmentRequest) SetBookingId(v string) {
	x.xxx_hidden_BookingId = v
}

type GetAppointmentRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	BookingId string
}

func (b0 GetAppointmentRequest_builder) Build() *GetAppointmentRequest {
	m0 := &GetAppointmentRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_BookingId = b.BookingId
	return m0
}

type DeleteAppointmentRequest struct {
	state                protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_BookingId string                 `protobuf:"bytes,1,opt,name=bookingId,proto3"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *DeleteAppointmentRequest) Reset() {
	*x = DeleteAppointmentRequest{}
	mi := &file_proto_schedulr_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAppointmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAppointmentRequest) ProtoMessage() {}

func (x *DeleteAppointmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedulr_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *DeleteAppointmentRequest) GetBookingId() string {
	if x != nil {
		return x.xxx_hidden_BookingId
	}
	return ""
}

func (x *DeleteAppointmentRequest) SetBookingId(v string) {
	x.xxx_hidden_BookingId = v
}

type DeleteAppointmentRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	BookingId string
}

func (b0 DeleteAppointmentRequest_builder) Build() *DeleteAppointmentRequest {
	m0 := &DeleteAppointmentRequest{}
	b, x := &b0, m0
	_, _ = b, x
	x.xxx_hidden_BookingId = b.BookingId
	return m0
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_proto_schedulr_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedulr_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type SubscribeRequest_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 SubscribeRequest_builder) Build() *SubscribeRequest {
	m0 := &SubscribeRequest{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

type Event struct {
	state           protoimpl.MessageState `protogen:"opaque.v1"`
	xxx_hidden_Data isEvent_Data           `protobuf_oneof:"data"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_proto_schedulr_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedulr_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (x *Event) GetBookingChanged() *BookingChangedEvent {
	if x != nil {
		if x, ok := x.xxx_hidden_Data.(*event_BookingChanged); ok {
			return x.BookingChanged
		}
	}
	return nil
}

func (x *Event) SetBookingChanged(v *BookingChangedEvent) {
	if v == nil {
		x.xxx_hidden_Data = nil
		return
	}
	x.xxx_hidden_Data = &event_BookingChanged{v}
}

func (x *Event) HasData() bool {
	if x == nil {
		return false
	}
	return x.xxx_hidden_Data != nil
}

func (x *Event) HasBookingChanged() bool {
	if x == nil {
		return false
	}
	_, ok := x.xxx_hidden_Data.(*event_BookingChanged)
	return ok
}

func (x *Event) ClearData() {
	x.xxx_hidden_Data = nil
}

func (x *Event) ClearBookingChanged() {
	if _, ok := x.xxx_hidden_Data.(*event_BookingChanged); ok {
		x.xxx_hidden_Data = nil
	}
}

const Event_Data_not_set_case case_Event_Data = 0
const Event_BookingChanged_case case_Event_Data = 1

func (x *Event) WhichData() case_Event_Data {
	if x == nil {
		return Event_Data_not_set_case
	}
	switch x.xxx_hidden_Data.(type) {
	case *event_BookingChanged:
		return Event_BookingChanged_case
	default:
		return Event_Data_not_set_case
	}
}

type Event_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

	// Fields of oneof xxx_hidden_Data:
	BookingChanged *BookingChangedEvent
	// -- end of xxx_hidden_Data
}

func (b0 Event_builder) Build() *Event {
	m0 := &Event{}
	b, x := &b0, m0
	_, _ = b, x
	if b.BookingChanged != nil {
		x.xxx_hidden_Data = &event_BookingChanged{b.BookingChanged}
	}
	return m0
}

type case_Event_Data protoreflect.FieldNumber

func (x case_Event_Data) String() string {
	md := file_proto_schedulr_proto_msgTypes[7].Descriptor()
	if x == 0 {
		return "not set"
	}
	return protoimpl.X.MessageFieldStringOf(md, protoreflect.FieldNumber(x))
}

type isEvent_Data interface {
	isEvent_Data()
}

type event_BookingChanged struct {
	BookingChanged *BookingChangedEvent `protobuf:"bytes,1,opt,name=bookingChanged,proto3,oneof"`
}

func (*event_BookingChanged) isEvent_Data() {}

type BookingChangedEvent struct {
	state         protoimpl.MessageState `protogen:"opaque.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BookingChangedEvent) Reset() {
	*x = BookingChangedEvent{}
	mi := &file_proto_schedulr_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BookingChangedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookingChangedEvent) ProtoMessage() {}

func (x *BookingChangedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_proto_schedulr_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

type BookingChangedEvent_builder struct {
	_ [0]func() // Prevents comparability and use of unkeyed literals for the builder.

}

func (b0 BookingChangedEvent_builder) Build() *BookingChangedEvent {
	m0 := &BookingChangedEvent{}
	b, x := &b0, m0
	_, _ = b, x
	return m0
}

var File_proto_schedulr_proto protoreflect.FileDescriptor

const file_proto_schedulr_proto_rawDesc = "" +
	"\n" +
	"\x14proto/schedulr.proto\x12\bschedulr\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/duration.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"}\n" +
	"\fAppointments\x129\n" +
	"\fappointments\x18\x01 \x03(\v2\x15.schedulr.AppointmentR\fappointments\x12#\n" +
	"\n" +
	"nextCursor\x18\x02 \x01(\tH\x00R\n" +
	"nextCursor\x88\x01\x01B\r\n" +
	"\v_nextCursor\"\xf6\x01\n" +
	"\vAppointment\x12\x1c\n" +
	"\tbookingId\x18\x01 \x01(\tR\tbookingId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12>\n" +
	"\fscheduledFor\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\fscheduledFor\x125\n" +
	"\bduration\x18\x04 \x01(\v2\x19.google.protobuf.DurationR\bduration\x12<\n" +
	"\vscheduledAt\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\vscheduledAt\"\xa9\x01\n" +
	"\x1aScheduleAppointmentRequest\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12>\n" +
	"\fscheduledFor\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\fscheduledFor\x125\n" +
	"\bduration\x18\x03 \x01(\v2\x19.google.protobuf.DurationR\bduration\"\xdc\x01\n" +
	"\x17ListAppointmentsRequest\x12\x1b\n" +
	"\x06cursor\x18\x01 \x01(\tH\x00R\x06cursor\x88\x01\x01\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x127\n" +
	"\x06before\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\x06before\x88\x01\x01\x125\n" +
	"\x05after\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x02R\x05after\x88\x01\x01B\t\n" +
	"\a_cursorB\t\n" +
	"\a_beforeB\b\n" +
	"\x06_after\"5\n" +
	"\x15GetAppointmentRequest\x12\x1c\n" +
	"\tbookingId\x18\x01 \x01(\tR\tbookingId\"8\n" +
	"\x18DeleteAppointmentRequest\x12\x1c\n" +
	"\tbookingId\x18\x01 \x01(\tR\tbookingId\"\x12\n" +
	"\x10SubscribeRequest\"X\n" +
	"\x05Event\x12G\n" +
	"\x0ebookingChanged\x18\x01 \x01(\v2\x1d.schedulr.BookingChangedEventH\x00R\x0ebookingChangedB\x06\n" +
	"\x04data\"\x15\n" +
	"\x13BookingChangedEvent2\xa5\x02\n" +
	"\x12AppointmentService\x12G\n" +
	"\bSchedule\x12$.schedulr.ScheduleAppointmentRequest\x1a\x15.schedulr.Appointment\x12A\n" +
	"\x04List\x12!.schedulr.ListAppointmentsRequest\x1a\x16.schedulr.Appointments\x12=\n" +
	"\x03Get\x12\x1f.schedulr.GetAppointmentRequest\x1a\x15.schedulr.Appointment\x12D\n" +
	"\x06Delete\x12\".schedulr.DeleteAppointmentRequest\x1a\x16.google.protobuf.Empty2J\n" +
	"\fEventService\x12:\n" +
	"\tSubscribe\x12\x1a.schedulr.SubscribeRequest\x1a\x0f.schedulr.Event0\x01B\tZ\a./protob\x06proto3"

var file_proto_schedulr_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_schedulr_proto_goTypes = []any{
	(*Appointments)(nil),               // 0: schedulr.Appointments
	(*Appointment)(nil),                // 1: schedulr.Appointment
	(*ScheduleAppointmentRequest)(nil), // 2: schedulr.ScheduleAppointmentRequest
	(*ListAppointmentsRequest)(nil),    // 3: schedulr.ListAppointmentsRequest
	(*GetAppointmentRequest)(nil),      // 4: schedulr.GetAppointmentRequest
	(*DeleteAppointmentRequest)(nil),   // 5: schedulr.DeleteAppointmentRequest
	(*SubscribeRequest)(nil),           // 6: schedulr.SubscribeRequest
	(*Event)(nil),                      // 7: schedulr.Event
	(*BookingChangedEvent)(nil),        // 8: schedulr.BookingChangedEvent
	(*timestamppb.Timestamp)(nil),      // 9: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),        // 10: google.protobuf.Duration
	(*emptypb.Empty)(nil),              // 11: google.protobuf.Empty
}
var file_proto_schedulr_proto_depIdxs = []int32{
	1,  // 0: schedulr.Appointments.appointments:type_name -> schedulr.Appointment
	9,  // 1: schedulr.Appointment.scheduledFor:type_name -> google.protobuf.Timestamp
	10, // 2: schedulr.Appointment.duration:type_name -> google.protobuf.Duration
	9,  // 3: schedulr.Appointment.scheduledAt:type_name -> google.protobuf.Timestamp
	9,  // 4: schedulr.ScheduleAppointmentRequest.scheduledFor:type_name -> google.protobuf.Timestamp
	10, // 5: schedulr.ScheduleAppointmentRequest.duration:type_name -> google.protobuf.Duration
	9,  // 6: schedulr.ListAppointmentsRequest.before:type_name -> google.protobuf.Timestamp
	9,  // 7: schedulr.ListAppointmentsRequest.after:type_name -> google.protobuf.Timestamp
	8,  // 8: schedulr.Event.bookingChanged:type_name -> schedulr.BookingChangedEvent
	2,  // 9: schedulr.AppointmentService.Schedule:input_type -> schedulr.ScheduleAppointmentRequest
	3,  // 10: schedulr.AppointmentService.List:input_type -> schedulr.ListAppointmentsRequest
	4,  // 11: schedulr.AppointmentService.Get:input_type -> schedulr.GetAppointmentRequest
	5,  // 12: schedulr.AppointmentService.Delete:input_type -> schedulr.DeleteAppointmentRequest
	6,  // 13: schedulr.EventService.Subscribe:input_type -> schedulr.SubscribeRequest
	1,  // 14: schedulr.AppointmentService.Schedule:output_type -> schedulr.Appointment
	0,  // 15: schedulr.AppointmentService.List:output_type -> schedulr.Appointments
	1,  // 16: schedulr.AppointmentService.Get:output_type -> schedulr.Appointment
	11, // 17: schedulr.AppointmentService.Delete:output_type -> google.protobuf.Empty
	7,  // 18: schedulr.EventService.Subscribe:output_type -> schedulr.Event
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_proto_schedulr_proto_init() }
func file_proto_schedulr_proto_init() {
	if File_proto_schedulr_proto != nil {
		return
	}
	file_proto_schedulr_proto_msgTypes[0].OneofWrappers = []any{}
	file_proto_schedulr_proto_msgTypes[3].OneofWrappers = []any{}
	file_proto_schedulr_proto_msgTypes[7].OneofWrappers = []any{
		(*event_BookingChanged)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_schedulr_proto_rawDesc), len(file_proto_schedulr_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_schedulr_proto_goTypes,
		DependencyIndexes: file_proto_schedulr_proto_depIdxs,
		MessageInfos:      file_proto_schedulr_proto_msgTypes,
	}.Build()
	File_proto_schedulr_proto = out.File
	file_proto_schedulr_proto_goTypes = nil
	file_proto_schedulr_proto_depIdxs = nil
}
